### ISSUE TITLE
0.4.1. on RubyGems is not the latest version of fxmlloader

### ISSUE THREAD

**Issue by bolandross** [byteit101/JRubyFX-FXMLLoader#10]
In the the latest version 0.4.1 on RubyGems, FXMLLoader doesn't seem to be the latest version.
The latest commit (3045dbd1bc1c53e76160593ce38d469d1e56c208) is **missing**!

Could you please make an update and upload it as 0.4.2 or so?

**Comment by byteit101** [comment]
Pushed 0.4.2!
