### ISSUE TITLE
generated file from fxml doesnt load a css

### ISSUE THREAD

**Issue by vpereira** [byteit101/JRubyFX-FXMLLoader#6]
I'm using jrubyfx. Always when I run my program, it generates with jruby-fxfxmlloader the cache file for my fxml, which doesn't load an external css file. inline css works right, but external css file doesnt. If I erase the cached file and run my app, the css is rendered and my dialogs are styled. with the cached version, it doesnt.

**Comment by byteit101** [comment]
JRubyFX 2.0 has been release, rendering this gem obsolete. If your issue still applies to JRubyFX 2.0, please reopen this issue on the JRubyFX issue tracker.
