### ISSUE TITLE
Logging causes error

### ISSUE THREAD

**Issue by Benbyday** [byteit101/JRubyFX-FXMLLoader#8]
In the value-elts.rb file on line 149 there is some kind of call to `Logging` when the versions of javafx/fxml don't match what is supported. I don't see where the gem that `Logging` is from is required and at one point it threw an error in my code indicating that the object/method was missing. It caused a lot of confusion because I couldn't tell if something was missing in my code, and when I figured it out, the solution on my end was as simple as deleting the encoding version in my fxml file. Should there be a different dependency list or something? Is it supposed to be the Logger class from the standard library?

**Comment by byteit101** [comment]
JRubyFX 2.0 has been release, rendering this gem obsolete. If your issue still applies to JRubyFX 2.0, please reopen this issue on the JRubyFX issue tracker.
